services:
  client:
    image: client
    ports:
      - 8080:5173
    volumes:
      - ../Speech-AI-client/src:/app/src    

  server:
    image: server
    volumes:
      - ./src:/app/src
    env_file:
      - .env



